config.rpc.host=localhost
config.rpc.port=10006
config.rpc.username=user1
config.rpc.password=test

server.port=10050
server.servlet.context-path=/

logging.level.root=INFO
logging.level.com.trace=DEBUG